apiVersion: v1
kind: Service
metadata:
  name: {{ include "registry.fullname" . }}-headless
  labels:
    {{- include "registry.labels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "registry.selectorLabels" . | nindent 4 }}