apiVersion: v1
kind: Service
metadata:
  name: {{ include "registry.fullname" . }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if eq .Values.service.type "NodePort"  }}
      nodePort: {{ .Values.service.nodePort | default 30000 }}
      {{- end }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "registry.selectorLabels" . | nindent 4 }}
